name: Welcome
email: me@bhargavg.com
description: "Wandering through Swift land"
meta_description: "Wandering through Swift land"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
exclude: [Rakefile]
domain_name: 'http://bhargavg.com'
google_analytics: 'UA-75144610-1'
gems: [jekyll-paginate, jekyll-gist, jekyll-sitemap]

# Details for the RSS feed generator
url:            'http://bhargavg.com'
author:         'Bhargav Gurlanka'
